services:
  migration:
    image: ghcr.io/the-developer-evolution/eternity:latest
    container_name: eternity-migration
    env_file:
      - .env
    command: prisma migrate deploy
    networks:
      - global_proxy

  seed:
    image: ghcr.io/the-developer-evolution/eternity:latest
    container_name: eternity-seed
    env_file:
      - .env
    command: prisma db seed
    depends_on:
      - migration
    networks:
      - global_proxy
    profiles:
      - manual

  studio:
    image: ghcr.io/the-developer-evolution/eternity:latest
    container_name: eternity-studio
    env_file:
      - .env
    command: prisma studio --port 5555
    expose:
      - "5555"
    depends_on:
      - migration
    networks:
      - global_proxy

  web:
    image: ghcr.io/the-developer-evolution/eternity:latest
    container_name: eternity
    expose:
      - 3000
    env_file:
      - .env
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
    depends_on:
      - migration
    networks:
      - global_proxy

networks:
  global_proxy:
    external: true
