services:
  migrate_reset:
    build:
      context: ./
      dockerfile: Dockerfile
      target: migrator
    container_name: eternity_migrate_reset
    command: pnpm prisma migrate reset --force
    env_file:
      - .env
    networks:
      - global_proxy
      - eternity_internal
    profiles:
      - manual
  seed:
    build:
      context: ./
      dockerfile: Dockerfile
      target: migrator
    container_name: eternity_seed
    command: /bin/sh -c "pnpm prisma generate && pnpm tsx prisma/seed.ts"
    env_file:
      - .env
    networks:
      - global_proxy
      - eternity_internal
    profiles:
      - manual
  studio:
    build:
      context: ./
      dockerfile: Dockerfile
      target: migrator
    container_name: eternity-studio
    command: pnpm prisma studio --port 5555 --hostname 0.0.0.0
    env_file:
      - .env
    expose:
      - "5555"
    networks:
      - global_proxy
      - eternity_internal
    profiles:
      - manual
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: runner
      args:
        - NEXT_PUBLIC_PUSHER_KEY=${NEXT_PUBLIC_PUSHER_KEY}
        - NEXT_PUBLIC_SOKETI_HOST=${NEXT_PUBLIC_SOKETI_HOST}
        - NEXT_PUBLIC_SOKETI_PORT=${NEXT_PUBLIC_SOKETI_PORT}
        - NEXT_PUBLIC_SOKETI_TLS=${NEXT_PUBLIC_SOKETI_TLS}
        - DATABASE_URL=${DATABASE_URL}
    container_name: eternity
    env_file:
      - .env
    expose:
      - "3000"
    networks:
      - global_proxy
      - eternity_internal

networks:
  global_proxy:
    external: true
  eternity_internal:
    driver: bridge