services:
  migrator:
    container_name: eternity-migrator
    image: ghcr.io/the-developer-evolution/eternity:latest
    command: npx prisma migrate deploy --url $$DATABASE_URL
    env_file:
      - .env
    networks:
      - npm_default

  app:
    container_name: eternity
    image: ghcr.io/the-developer-evolution/eternity:latest
    depends_on:
      migrator:
        condition: service_completed_successfully
    env_file:
      - .env
    expose:
      - 3000
    networks:
      - npm_default
