-- AlterTable
ALTER TABLE "CraftPeriod" ALTER COLUMN "price" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "CraftStockPeriod" ALTER COLUMN "price" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "PeriodeTrading" ALTER COLUMN "cost_map" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "price_map" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "usdidr_rate" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "RawPeriod" ALTER COLUMN "price" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "RawStockPeriod" ALTER COLUMN "price" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "TradingData" ALTER COLUMN "idr" SET DEFAULT -10000000000,
ALTER COLUMN "idr" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "usd" SET DEFAULT 0,
ALTER COLUMN "usd" SET DATA TYPE DECIMAL(65,30);
