-- AlterTable
ALTER TABLE "TradingData" ALTER COLUMN "idr" SET DEFAULT -10000000000,
ALTER COLUMN "usd" SET DEFAULT 0,
ALTER COLUMN "eternites" SET DEFAULT 0,
ALTER COLUMN "map" SET DEFAULT 0,
ALTER COLUMN "point" SET DEFAULT 0;
